### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [gan74/Yave#3]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114118468-73bf0f80-991b-11eb-8d62-021bfbf92476.png)

thank you  
best regards to you  
William

**Comment by gan74** [comment]
Hi!

glslc should come with the Vulkan SDK. 
The problem here is that the CMakeLists just blindly call `glslc` , which will fail if the SDK hasn't been added to PATH.

Note that the project only works on Windows right now. There is nothing preventing it to run on other OSes, I just haven't code ported the windowing code (which uses Win32 API).

**Comment by gan74** [comment]
Should be fixed by 5a01ecc
You'll need to update CMake though.
